/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;
import javax.swing.*;
import java.awt.*;


/**
 *
 * @author julio
 */
public class inicio extends javax.swing.JFrame {

    
   
    public inicio() {
         this.setExtendedState(MAXIMIZED_BOTH);
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbltitulo = new javax.swing.JLabel();
        btnsalir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnventas = new javax.swing.JButton();
        btncompras = new javax.swing.JButton();
        btninventario = new javax.swing.JButton();
        btnpagoaproveedores = new javax.swing.JButton();
        btnproveedores = new javax.swing.JButton();
        btnvencimiento = new javax.swing.JButton();
        btnreporteventas = new javax.swing.JButton();
        btnreportecompras = new javax.swing.JButton();
        btnpagodeclientes = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        lblusuario = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(null);

        lbltitulo.setFont(new java.awt.Font("Engravers MT", 3, 38)); // NOI18N
        lbltitulo.setText("FARMACIA LA SALUD");
        getContentPane().add(lbltitulo);
        lbltitulo.setBounds(20, 0, 1640, 90);

        btnsalir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        btnsalir.setText("Salir");
        btnsalir.setBorder(null);
        btnsalir.setBorderPainted(false);
        btnsalir.setContentAreaFilled(false);
        btnsalir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnsalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnsalir.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir1.png"))); // NOI18N
        btnsalir.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnsalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnsalir);
        btnsalir.setBounds(30, 560, 120, 120);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrarsesion.jpg"))); // NOI18N
        jButton1.setText("Cerrar Sesion");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(160, 560, 130, 120);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bayer.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 100, 225, 220);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/farmace.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(290, 100, 240, 220);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mk.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(300, 340, 230, 200);

        jPanel1.setBackground(new java.awt.Color(81, 220, 238));
        jPanel1.setBorder(null);
        jPanel1.setToolTipText("");
        jPanel1.setLayout(null);

        btnventas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ventas.jpg"))); // NOI18N
        btnventas.setText("ventas");
        btnventas.setBorder(null);
        btnventas.setBorderPainted(false);
        btnventas.setContentAreaFilled(false);
        btnventas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnventas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnventas.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ventas1.jpg"))); // NOI18N
        btnventas.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnventas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnventasActionPerformed(evt);
            }
        });
        jPanel1.add(btnventas);
        btnventas.setBounds(70, 120, 80, 106);

        btncompras.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btncompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/compras.jpg"))); // NOI18N
        btncompras.setText("Compras");
        btncompras.setBorder(null);
        btncompras.setBorderPainted(false);
        btncompras.setContentAreaFilled(false);
        btncompras.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btncompras.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btncompras.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/compras1.jpg"))); // NOI18N
        btncompras.setVerifyInputWhenFocusTarget(false);
        btncompras.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btncompras.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btncompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncomprasActionPerformed(evt);
            }
        });
        jPanel1.add(btncompras);
        btncompras.setBounds(270, 120, 80, 106);

        btninventario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btninventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/existencias.jpg"))); // NOI18N
        btninventario.setText("Inventario");
        btninventario.setBorder(null);
        btninventario.setBorderPainted(false);
        btninventario.setContentAreaFilled(false);
        btninventario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btninventario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btninventario.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/existencias1.jpg"))); // NOI18N
        btninventario.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btninventario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btninventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninventarioActionPerformed(evt);
            }
        });
        jPanel1.add(btninventario);
        btninventario.setBounds(450, 120, 110, 110);

        btnpagoaproveedores.setText("Pagos a Proveedores");
        btnpagoaproveedores.setBorder(null);
        btnpagoaproveedores.setBorderPainted(false);
        btnpagoaproveedores.setContentAreaFilled(false);
        btnpagoaproveedores.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnpagoaproveedores.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnpagoaproveedores.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnpagoaproveedores.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnpagoaproveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpagoaproveedoresActionPerformed(evt);
            }
        });
        jPanel1.add(btnpagoaproveedores);
        btnpagoaproveedores.setBounds(420, 550, 170, 110);

        btnproveedores.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnproveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/proveedor.png"))); // NOI18N
        btnproveedores.setText("Proveedores");
        btnproveedores.setBorder(null);
        btnproveedores.setBorderPainted(false);
        btnproveedores.setContentAreaFilled(false);
        btnproveedores.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnproveedores.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnproveedores.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/proveedor1.png"))); // NOI18N
        btnproveedores.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnproveedores.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnproveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnproveedoresActionPerformed(evt);
            }
        });
        jPanel1.add(btnproveedores);
        btnproveedores.setBounds(250, 260, 120, 110);

        btnvencimiento.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnvencimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/inventario.jpg"))); // NOI18N
        btnvencimiento.setText("Caducidad y Existencia");
        btnvencimiento.setBorder(null);
        btnvencimiento.setBorderPainted(false);
        btnvencimiento.setContentAreaFilled(false);
        btnvencimiento.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnvencimiento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnvencimiento.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/inventario1.jpg"))); // NOI18N
        btnvencimiento.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnvencimiento.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnvencimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvencimientoActionPerformed(evt);
            }
        });
        jPanel1.add(btnvencimiento);
        btnvencimiento.setBounds(10, 260, 190, 110);

        btnreporteventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reporteventas.jpg"))); // NOI18N
        btnreporteventas.setText("Reporte Ventas");
        btnreporteventas.setBorder(null);
        btnreporteventas.setBorderPainted(false);
        btnreporteventas.setContentAreaFilled(false);
        btnreporteventas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnreporteventas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnreporteventas.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reporteventas1.jpg"))); // NOI18N
        btnreporteventas.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnreporteventas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnreporteventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreporteventasActionPerformed(evt);
            }
        });
        jPanel1.add(btnreporteventas);
        btnreporteventas.setBounds(50, 410, 110, 110);

        btnreportecompras.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnreportecompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reportecompras.png"))); // NOI18N
        btnreportecompras.setText("Reporte Compras");
        btnreportecompras.setBorder(null);
        btnreportecompras.setBorderPainted(false);
        btnreportecompras.setContentAreaFilled(false);
        btnreportecompras.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnreportecompras.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnreportecompras.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reportecompras1.png"))); // NOI18N
        btnreportecompras.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnreportecompras.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnreportecompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreportecomprasActionPerformed(evt);
            }
        });
        jPanel1.add(btnreportecompras);
        btnreportecompras.setBounds(250, 410, 120, 110);

        btnpagodeclientes.setText("Pago de Clientes");
        btnpagodeclientes.setBorder(null);
        btnpagodeclientes.setBorderPainted(false);
        btnpagodeclientes.setContentAreaFilled(false);
        btnpagodeclientes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnpagodeclientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnpagodeclientes.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnpagodeclientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnpagodeclientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpagodeclientesActionPerformed(evt);
            }
        });
        jPanel1.add(btnpagodeclientes);
        btnpagodeclientes.setBounds(430, 410, 150, 110);

        jButton2.setText("Creacion Productos");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(240, 550, 150, 110);
        jButton2.getAccessibleContext().setAccessibleName("Creacion\n Productos");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("MODULO DE OPERACION ");
        jLabel5.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel1.add(jLabel5);
        jLabel5.setBounds(70, 40, 360, 50);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/clientes.jpg"))); // NOI18N
        jButton3.setText("Clientes");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/clientes1.jpg"))); // NOI18N
        jButton3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(460, 260, 80, 110);
        jPanel1.add(lblusuario);
        lblusuario.setBounds(420, 90, 130, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(580, 10, 630, 680);

        jPanel2.setBackground(java.awt.Color.white);
        getContentPane().add(jPanel2);
        jPanel2.setBounds(-10, -10, 1250, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
     dispose();
     System.exit(0);
      
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btncomprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncomprasActionPerformed
      new compras2().setVisible(true);
      dispose();
    }//GEN-LAST:event_btncomprasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new login().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnventasActionPerformed
        new ventas().setVisible(true);
        
    }//GEN-LAST:event_btnventasActionPerformed

    private void btnproveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnproveedoresActionPerformed
    new proveedores().setVisible(true);
    dispose();
    }//GEN-LAST:event_btnproveedoresActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new clientes().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       new productos().setVisible(true);
       dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnpagoaproveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpagoaproveedoresActionPerformed
       new pago_proveedores().setVisible(true);
       dispose();
    }//GEN-LAST:event_btnpagoaproveedoresActionPerformed

    private void btnpagodeclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpagodeclientesActionPerformed
        new pago_clientes().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnpagodeclientesActionPerformed

    private void btnreporteventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreporteventasActionPerformed
        new reporteventas().setVisible(true);
    }//GEN-LAST:event_btnreporteventasActionPerformed

    private void btninventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninventarioActionPerformed
        new inventario().setVisible(true);
        dispose();
    }//GEN-LAST:event_btninventarioActionPerformed

    private void btnvencimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvencimientoActionPerformed
        new vencimiento().setVisible(true);
        
    }//GEN-LAST:event_btnvencimientoActionPerformed

    private void btnreportecomprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreportecomprasActionPerformed
      new reportecompras().setVisible(true);
    }//GEN-LAST:event_btnreportecomprasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicio().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncompras;
    private javax.swing.JButton btninventario;
    private javax.swing.JButton btnpagoaproveedores;
    private javax.swing.JButton btnpagodeclientes;
    private javax.swing.JButton btnproveedores;
    private javax.swing.JButton btnreportecompras;
    private javax.swing.JButton btnreporteventas;
    private javax.swing.JButton btnsalir;
    private javax.swing.JButton btnvencimiento;
    private javax.swing.JButton btnventas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbltitulo;
    public static javax.swing.JLabel lblusuario;
    // End of variables declaration//GEN-END:variables
}
