/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Formularios.inicio;
import base_datos.mysql;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;
import com.placeholder.PlaceHolder;



    /**
 *
 * @author Angel
 */
public class login extends javax.swing.JFrame {

    mysql con;
    ResultSet rs;
    int ID=-1;
    ImageIcon iconolbl = new ImageIcon("src/imagenes/logincian.png");
    
    /** Creates new form inicio */
    public login() {
        initComponents();
        PlaceHolder user = new PlaceHolder(txtusuario, "Usuario");
        PlaceHolder pass = new PlaceHolder(txtpassword, "Contraseña");
        iconuser.setIcon(iconolbl);
        iconuser.setIconTextGap(1);
        iconuser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconuser.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
        iconuser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        iconuser.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
         try {
         
       con = new mysql();

        } catch (Exception ex) {
         
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iconuser = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        txtpassword = new javax.swing.JPasswordField();
        jBingresar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(null);
        getContentPane().setLayout(null);

        iconuser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(iconuser);
        iconuser.setBounds(70, 30, 320, 150);

        txtusuario.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N
        txtusuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtusuario);
        txtusuario.setBounds(100, 180, 260, 40);
        txtusuario.getAccessibleContext().setAccessibleName("");
        txtusuario.getAccessibleContext().setAccessibleDescription("");

        txtpassword.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        txtpassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpasswordActionPerformed(evt);
            }
        });
        txtpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpasswordKeyPressed(evt);
            }
        });
        getContentPane().add(txtpassword);
        txtpassword.setBounds(100, 260, 260, 40);

        jBingresar.setBackground(new java.awt.Color(8, 142, 160));
        jBingresar.setForeground(java.awt.Color.white);
        jBingresar.setText("Login");
        jBingresar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jBingresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBingresarActionPerformed(evt);
            }
        });
        getContentPane().add(jBingresar);
        jBingresar.setBounds(100, 340, 260, 40);

        jPanel2.setBackground(java.awt.Color.white);
        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(jPanel2);
        jPanel2.setBounds(70, 140, 320, 310);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 520, 490);

        setSize(new java.awt.Dimension(481, 516));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusuarioActionPerformed

    private void txtpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpasswordActionPerformed

    private void jBingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBingresarActionPerformed
  // BOTON PARA INGRESAR AL SISTEMA
        
        // se obtiene los valores de los cuadros de texto
        String usuario=txtusuario.getText();
           String pass=txtpassword.getText();
           
           String nom="",password="",id="",nivel="";
        String nombre = null;
        String ap = null;
        String am = null;
           
           // se valida que no esten vacios
           if(usuario.equals("") || pass.equals(""))
               {
                JOptionPane.showMessageDialog(null,"Faltan campos por llenar");
               }
           else{

               
               
               try {
                   // se hace la conexion con la base de datos
            con = new mysql();
            
            //sentencia sql para extraer los datos del usuario insertado
           String sql = "select * from usuarios where user='"+usuario+"';";
           
                      
           rs = con.Consulta(sql); 
           
       // se obtienen los datos de la consulta
         
                while (rs.next()){
                    id = rs.getString(1);
                     nombre= rs.getString(2);
                    ap= rs.getString(3);
                    am = rs.getString(4);
                    nom = rs.getString(5);
                    password = rs.getString(6);
                    nivel= rs.getString(7);
                }
                if (id.equals("")) {
           
               JOptionPane.showMessageDialog(null,"Usuario No Encontrado");
                    txtusuario.setText("");
                    txtpassword.setText("");
           
           }
           else{
                ID = Integer.parseInt(id);
                int N = Integer.parseInt(nivel);
              
                
                // se compara que el usuario de la base de datos es el mismo que el insertado
                //se comparan ambas contraseñas encriptadas
                
                if(nom.equals(usuario)){
                    if(pass.equals(password)){
                    // se compara si el estatus es igual a TRUE
                    if(N==0){
                        //se carga la segunda interfaz
                        inicio inter = new inicio();
                       // inter.IDusuario = ID;
                        JOptionPane.showMessageDialog(rootPane, "Bienvenid@ "+nombre+" "+ap+" "+am+" \n\n Has entrado al sistema como: Administrador");
                        inter.setVisible(true); 
                        this.dispose();
                    }
                    
                                      
                }
                    else{
                    
                        JOptionPane.showMessageDialog(null,"Contraseña Incorrecta");
                        txtusuario.setText("");
                        txtpassword.setText("");
                    }
                }
                // en caso de que esten mal los datos
                else{
                    JOptionPane.showMessageDialog(null,"Usuario o Contraseña Incorrecta");
                    txtusuario.setText("");
                    txtpassword.setText("");
                }
                
      
           }
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,"no hay usuarios");
        }             
               

               }

    
    }//GEN-LAST:event_jBingresarActionPerformed

    private void txtpasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpasswordKeyPressed
       
        int evento=evt.getKeyCode();
        int N;
if(evento==10 ){
      String usuario=txtusuario.getText();
           String pass=txtpassword.getText();
           
           String nom="",password="",id="",nivel="",nombre="", ap="",am="";
           
           // se valida que no esten vacios
           if(usuario.equals("") || pass.equals(""))
               {
                JOptionPane.showMessageDialog(null,"Faltan campos por llenar");
               }
           else{

               
               
               try {
                   // se hace la conexion con la base de datos
            con = new mysql();
            
            //sentencia sql para extraer los datos del usuario insertado
           String sql = "select * from usuarios where user='"+usuario+"';";
           
                      
           rs = con.Consulta(sql); 
       // se obtienen los datos de la consulta
         
                while (rs.next()){
                    id = rs.getString(1);
                    nombre= rs.getString(2);
                    ap= rs.getString(3);
                    am = rs.getString(4);
                    nom = rs.getString(5);
                    password = rs.getString(6);
                    nivel= rs.getString(7);
                }
                if (id.equals("")) {
           
               JOptionPane.showMessageDialog(null,"Usuario No Encontrado");
                    txtusuario.setText("");
                    txtpassword.setText("");
           
           }
           else{
                ID = Integer.parseInt(id);
                N = Integer.parseInt(nivel);
            
                // se compara que el usuario de la base de datos es el mismo que el insertado
                //se comparan ambas contraseñas encriptadas
                if(nom.equals(usuario) && pass.equals(password)){
                    // se compara si el estatus es igual a TRUE
                    if(N==0){
                        //se carga la segunda interfaz
                        inicio inter = new inicio();
                        JOptionPane.showMessageDialog(rootPane, "Bienvenid@ "+nombre+" "+ap+" "+am+" \n\n Has entrado al sistema como: Administrador");
                        inter.setVisible(true); 
                        //login.lblusuario.setText(txtusuario.getText());
                        this.dispose();
                    }
                                     
                   
                }
                
                // en caso de que esten mal los datos
                else{
                    JOptionPane.showMessageDialog(rootPane,"Contraseña Incorrecta");
                    txtusuario.setText("");
                    txtpassword.setText("");
                    
                }
                
                }
          
            
        } catch (Exception ex) {
                         
               JOptionPane.showMessageDialog(null,"no hay usuarios");

               }

    
}
}    
    }//GEN-LAST:event_txtpasswordKeyPressed
/**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
                
}
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconuser;
    private javax.swing.JButton jBingresar;
    private javax.swing.JLabel jLabel1;
    public transient javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField txtpassword;
    public static javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
